MOUSEKEY_ENABLE = no    # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
WPM_ENABLE 			= yes
LTO_ENABLE      = yes
TAP_DANCE_ENABLE = no
BOOTLOADER = atmel-dfu
CAPS_WORD_ENABLE = yes
