MOUSEKEY_ENABLE = no    # Mouse keys
EXTRAKEY_ENABLE = yes		# Media keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
WPM_ENABLE 			= yes
LTO_ENABLE      = yes
TAP_DANCE_ENABLE = no
BOOTLOADER = atmel-dfu
CAPS_WORD_ENABLE = yes
